"""
Multi-format report generation for simulation analysis results.

Generates reports in three formats:
  - Markdown: Lab-ready reports with tables and equations
  - JSON: Programmatic integration and database storage
  - HTML: Interactive dashboards with styled CSS

Main Classes:
  - ReportGenerator: Main report generator

Usage:
    gen = ReportGenerator(log)
    gen.generate_markdown(issues, "report.md")
    gen.generate_json(issues, "report.json")
    gen.generate_html(issues, "report.html")
"""

from datetime import datetime
from pathlib import Path
from typing import Optional

from jinja2 import Template

from src.analyzers import Issue, SeverityLevel
from src.parsers import AspectLog


class ReportGenerator:
    """Generate analysis reports in multiple formats."""

    MARKDOWN_TEMPLATE = r"""
# ASPECT Simulation Analysis Report

**Generated:** {{ generated_at }}  
**Log File:** {{ log_file }}  
**ASPECT Version:** {{ aspect_version }}  
**Material Model:** {{ material_model }}

## Executive Summary

{{ summary }}

### Key Metrics

| Metric | Value |
|--------|-------|
| Total Timesteps | {{ total_timesteps }} |
| Completed Timesteps | {{ completed_timesteps }} |
| Failed Timesteps | {{ failed_timesteps }} |
| Total Wall Time | {{ total_wall_time_seconds | round(1) }} s |
| Avg Time/Timestep | {{ avg_wall_time_seconds | round(2) }} s |

## Critical Issues

{% if critical_issues %}
{% for issue in critical_issues %}
### 🔴 {{ issue.title }}
- **Category:** {{ issue.category }}
- **Timestep:** {{ issue.timestep or 'N/A' }}
- **Description:** {{ issue.description }}
- **Suggested Fix:**
```
{{ issue.suggested_fix }}
```
{% endfor %}
{% else %}
✅ No critical issues detected.
{% endif %}

## Error-Level Issues

{% if error_issues %}
{% for issue in error_issues %}
### 🟠 {{ issue.title }}
- **Category:** {{ issue.category }}
- **Timestep:** {{ issue.timestep or 'N/A' }}
- **Description:** {{ issue.description }}
- **Suggested Fix:**
```
{{ issue.suggested_fix }}
```
{% endfor %}
{% else %}
✅ No error-level issues detected.
{% endif %}

## Warnings

{% if warning_issues %}
{% for issue in warning_issues %}
### 🟡 {{ issue.title }}
- **Category:** {{ issue.category }}
- **Description:** {{ issue.description }}

**Metrics:**
{% for key, val in issue.metrics.items() %}
- {{ key }}: {{ val }}
{% endfor %}
{% endfor %}
{% else %}
✅ No warnings.
{% endif %}

## Timestep Analysis

### Timestep Statistics

| # | Time (yr) | dt (yr) | Wall Time (s) | Lin. Iters | Status |
|---|-----------|---------|---------------|------------|--------|
{% for ts in timesteps %}
| {{ ts.number }} | {{ "%.2e" | format(ts.time) }} | {{ "%.2e" | format(ts.time_step_size) }} | {{ "%.2f" | format(ts.wall_time_seconds) }} | {{ ts.avg_linear_iterations | round(0) | int }} | {% if ts.failed %}❌{% else %}✅{% endif %} |
{% endfor %}

## Solver Statistics

### Linear Solver Performance

{% for ts in timesteps if ts.linear_solvers %}
#### Timestep {{ ts.number }}

| Solver | Iterations | Residual | Target | Converged |
|--------|-----------|----------|--------|----------|
{% for solver in ts.linear_solvers %}
| {{ solver.solver_type.value }} | {{ solver.iterations }} | {{ "%.2e" | format(solver.residual) }} | {{ "%.2e" | format(solver.iteration_target) }} | {% if solver.converged %}✅{% else %}❌{% endif %} |
{% endfor %}

{% endfor %}

## Recommendations

{% if has_critical %}
⚠️ **CRITICAL:** This simulation has failed. Review suggested fixes above.
{% elif has_errors %}
⚠️ **ERRORS DETECTED:** Review error-level issues and implement fixes before next run.
{% else %}
✅ **Simulation appears healthy.** Monitor performance trends for degradation.
{% endif %}

---
*Report generated by aspect-hpc-ai-monitor v0.1.0*
    """

    def __init__(self, log: AspectLog):
        """
        Initialize report generator.

        Args:
            log: AspectLog object from parser
        """
        self.log = log
        self.generated_at = datetime.now().isoformat()

    def generate_markdown(self, issues: list[Issue], output_path: Optional[Path | str] = None) -> str:
        """
        Generate Markdown report.

        Args:
            issues: List of detected issues
            output_path: Optional file path to write report

        Returns:
            Markdown report as string
        """
        critical = [i for i in issues if i.severity == SeverityLevel.CRITICAL]
        errors = [i for i in issues if i.severity == SeverityLevel.ERROR]
        warnings = [i for i in issues if i.severity == SeverityLevel.WARNING]

        completed = len([ts for ts in self.log.timesteps if not ts.failed])
        total = len(self.log.timesteps)
        failed = len(self.log.failed_timesteps)

        template = Template(self.MARKDOWN_TEMPLATE)
        report = template.render(
            generated_at=self.generated_at,
            log_file=self.log.__class__.__name__,
            aspect_version=self.log.aspect_version,
            material_model=self.log.material_model,
            summary=self._generate_summary(issues),
            total_timesteps=total,
            completed_timesteps=completed,
            failed_timesteps=failed,
            total_wall_time_seconds=self.log.total_wall_time,
            avg_wall_time_seconds=self.log.avg_wall_time_per_timestep,
            critical_issues=critical,
            error_issues=errors,
            warning_issues=warnings,
            has_critical=len(critical) > 0,
            has_errors=len(errors) > 0,
            timesteps=self.log.timesteps,
        )

        if output_path:
            output_path = Path(output_path)
            output_path.parent.mkdir(parents=True, exist_ok=True)
            with open(output_path, "w") as f:
                f.write(report)

        return report

    def generate_json(self, issues: list[Issue], output_path: Optional[Path | str] = None) -> dict:
        """
        Generate JSON report.

        Args:
            issues: List of detected issues
            output_path: Optional file path to write report

        Returns:
            Dictionary with all data (JSON-serializable)
        """
        import json

        completed = len([ts for ts in self.log.timesteps if not ts.failed])
        total = len(self.log.timesteps)

        timestep_data = []
        for ts in self.log.timesteps:
            ts_dict = {
                "number": ts.number,
                "time": ts.time,
                "dt": ts.time_step_size,
                "wall_time_seconds": ts.wall_time_seconds,
                "failed": ts.failed,
                "failure_type": ts.failure_type,
                "has_nan": ts.has_nan,
                "has_divergence": ts.has_divergence,
                "avg_linear_iterations": ts.avg_linear_iterations,
                "max_linear_iterations": ts.max_linear_iterations,
            }
            timestep_data.append(ts_dict)

        issue_data = []
        for issue in issues:
            issue_dict = {
                "severity": issue.severity.value,
                "category": issue.category,
                "title": issue.title,
                "description": issue.description,
                "timestep": issue.timestep,
                "suggested_fix": issue.suggested_fix,
                "metrics": issue.metrics,
            }
            issue_data.append(issue_dict)

        report = {
            "metadata": {
                "generated_at": self.generated_at,
                "version": "0.1.0",
            },
            "simulation": {
                "aspect_version": self.log.aspect_version,
                "material_model": self.log.material_model,
            },
            "summary": {
                "total_timesteps": total,
                "completed_timesteps": completed,
                "failed_timesteps": len(self.log.failed_timesteps),
                "total_wall_time_seconds": self.log.total_wall_time,
                "avg_wall_time_per_timestep": self.log.avg_wall_time_per_timestep,
            },
            "issues": {
                "total": len(issues),
                "critical": len([i for i in issues if i.severity == SeverityLevel.CRITICAL]),
                "errors": len([i for i in issues if i.severity == SeverityLevel.ERROR]),
                "warnings": len([i for i in issues if i.severity == SeverityLevel.WARNING]),
                "list": issue_data,
            },
            "timesteps": timestep_data,
        }

        if output_path:
            output_path = Path(output_path)
            output_path.parent.mkdir(parents=True, exist_ok=True)
            with open(output_path, "w") as f:
                json.dump(report, f, indent=2)

        return report

    def generate_html(self, issues: list[Issue], output_path: Optional[Path | str] = None) -> str:
        """
        Generate HTML report.

        Args:
            issues: List of detected issues
            output_path: Optional file path to write report

        Returns:
            HTML report as string
        """
        critical = [i for i in issues if i.severity == SeverityLevel.CRITICAL]
        errors = [i for i in issues if i.severity == SeverityLevel.ERROR]
        warnings = [i for i in issues if i.severity == SeverityLevel.WARNING]

        completed = len([ts for ts in self.log.timesteps if not ts.failed])
        total = len(self.log.timesteps)

        html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ASPECT Simulation Report</title>
    <style>
        * {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; }}
        body {{ background: #f5f5f5; margin: 0; padding: 20px; }}
        .container {{ max-width: 1200px; margin: 0 auto; background: white; padding: 30px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }}
        h1 {{ color: #333; border-bottom: 3px solid #0066cc; padding-bottom: 10px; }}
        h2 {{ color: #0066cc; margin-top: 30px; }}
        .summary {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 20px; margin: 20px 0; }}
        .stat {{ background: #f9f9f9; padding: 15px; border-radius: 8px; text-align: center; border-left: 4px solid #0066cc; }}
        .stat-value {{ font-size: 24px; font-weight: bold; color: #0066cc; }}
        .stat-label {{ color: #666; margin-top: 5px; }}
        .critical {{ border-left-color: #dc3545; }}
        .error {{ border-left-color: #ff9800; }}
        .warning {{ border-left-color: #ffc107; }}
        .success {{ border-left-color: #28a745; }}
        table {{ width: 100%; border-collapse: collapse; margin: 20px 0; }}
        th {{ background: #0066cc; color: white; padding: 12px; text-align: left; }}
        td {{ padding: 10px; border-bottom: 1px solid #ddd; }}
        tr:hover {{ background: #f5f5f5; }}
        .issue {{ margin: 15px 0; padding: 15px; border-left: 4px solid; background: #f9f9f9; }}
        .critical-issue {{ border-left-color: #dc3545; }}
        .error-issue {{ border-left-color: #ff9800; }}
        .warning-issue {{ border-left-color: #ffc107; }}
        .issue-title {{ font-weight: bold; font-size: 16px; }}
        .issue-desc {{ margin-top: 5px; color: #555; }}
        .issue-fix {{ margin-top: 10px; padding: 10px; background: white; border-radius: 4px; font-family: monospace; font-size: 12px; }}
        .footer {{ margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; color: #999; font-size: 12px; text-align: center; }}
    </style>
</head>
<body>
    <div class="container">
        <h1>ASPECT Simulation Analysis Report</h1>
        <p><strong>Generated:</strong> {self.generated_at}</p>
        <p><strong>ASPECT Version:</strong> {self.log.aspect_version}</p>
        <p><strong>Material Model:</strong> {self.log.material_model}</p>

        <h2>Summary</h2>
        <div class="summary">
            <div class="stat success">
                <div class="stat-value">{completed}/{total}</div>
                <div class="stat-label">Timesteps Completed</div>
            </div>
            {f'<div class="stat critical"><div class="stat-value">{len(critical)}</div><div class="stat-label">Critical Issues</div></div>' if len(critical) > 0 else ''}
            {f'<div class="stat error"><div class="stat-value">{len(errors)}</div><div class="stat-label">Errors</div></div>' if len(errors) > 0 else ''}
            {f'<div class="stat warning"><div class="stat-value">{len(warnings)}</div><div class="stat-label">Warnings</div></div>' if len(warnings) > 0 else ''}
            <div class="stat">
                <div class="stat-value">{self.log.total_wall_time:.1f}s</div>
                <div class="stat-label">Total Wall Time</div>
            </div>
        </div>

        <h2>Critical Issues</h2>
        {''.join(f'''<div class="issue critical-issue">
            <div class="issue-title">🔴 {issue.title}</div>
            <div class="issue-desc">{issue.description}</div>
            <div class="issue-fix"><strong>Fix:</strong> {issue.suggested_fix.replace(chr(10), '<br>')}</div>
        </div>''' for issue in critical) if critical else '<p>✅ No critical issues</p>'}

        <h2>Error-Level Issues</h2>
        {''.join(f'''<div class="issue error-issue">
            <div class="issue-title">🟠 {issue.title}</div>
            <div class="issue-desc">{issue.description}</div>
        </div>''' for issue in errors) if errors else '<p>✅ No errors</p>'}

        <div class="footer">
            <p>Generated by aspect-hpc-ai-monitor v0.1.0 | {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
        </div>
    </div>
</body>
</html>"""

        if output_path:
            output_path = Path(output_path)
            output_path.parent.mkdir(parents=True, exist_ok=True)
            with open(output_path, "w") as f:
                f.write(html)

        return html

    @staticmethod
    def _generate_summary(issues: list[Issue]) -> str:
        """Generate text summary from issues."""
        critical = len([i for i in issues if i.severity == SeverityLevel.CRITICAL])
        errors = len([i for i in issues if i.severity == SeverityLevel.ERROR])
        warnings = len([i for i in issues if i.severity == SeverityLevel.WARNING])

        if critical > 0:
            return (
                f"⚠️ **Critical issues detected ({critical}).** "
                f"Simulation has failed and requires intervention."
            )
        elif errors > 0:
            return (
                f"⚠️ **Error-level issues found ({errors}).** "
                f"Review and implement fixes before next run."
            )
        elif warnings > 0:
            return f"✅ **Simulation completed successfully** with {warnings} warnings to monitor."
        else:
            return "✅ **Simulation completed successfully** with no issues detected."
