"""ReportGenerator for creating reports from analysis results."""

import os
from datetime import datetime


class ReportGenerator:
    """Generate reports from parser and analyzer results."""

    def __init__(self, parser, analyzer, output_dir='reports'):
        """Initialize the report generator.

        Args:
            parser: AspectLogParser instance with log data.
            analyzer: SimulationAnalyzer instance with analysis results.
            output_dir: Directory to save reports.
        """
        self.parser = parser
        self.analyzer = analyzer
        self.output_dir = output_dir
        self._ensure_output_dir()

    def _ensure_output_dir(self):
        """Create output directory if it doesn't exist."""
        if not os.path.exists(self.output_dir):
            os.makedirs(self.output_dir)

    def generate_markdown_report(self, filename=None):
        """Generate a markdown report.

        Args:
            filename: Optional filename for the report.
                     Defaults to timestamp-based name.

        Returns:
            Path to the generated markdown report.
        """
        if filename is None:
            timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
            filename = f'report_{timestamp}.md'

        filepath = os.path.join(self.output_dir, filename)

        # Get summaries
        parser_summary = self.parser.summarize()
        analyzer_summary = self.analyzer.get_summary()

        # Build markdown content
        content = f"""# ASPECT Simulation Report

Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## Parser Summary

- Total Lines: {parser_summary['total_lines']}
- Errors Found: {parser_summary['errors_count']}
- Timesteps Found: {parser_summary['timesteps_count']}

## Analysis Results

### Issues Detected

| Issue Type | Count |
|---|---|
| Total Errors | {analyzer_summary['total_errors']} |
| Failed Operations | {analyzer_summary['total_failures']} |
| Convergence Issues | {analyzer_summary['convergence_issues']} |
| Solver Warnings | {analyzer_summary['solver_warnings']} |
| NaN Occurrences | {analyzer_summary['nan_count']} |
| Memory Issues | {analyzer_summary['memory_issues']} |
| Timesteps Completed | {analyzer_summary['timesteps_completed']} |

## Detailed Findings

### Errors

"""
        for error in self.analyzer.analysis_results['error_lines'][:10]:
            content += f"- {error}\n"

        if len(self.analyzer.analysis_results['error_lines']) > 10:
            content += f"- ... and {len(self.analyzer.analysis_results['error_lines']) - 10} more\n"

        content += f"\n### Convergence Failures\n\n"
        for failure in self.analyzer.analysis_results['convergence_failures'][:5]:
            content += f"- {failure}\n"

        content += f"\n---\nReport generated by aspect-hpc-ai-monitor\n"

        with open(filepath, 'w') as f:
            f.write(content)

        return filepath

    def generate_text_report(self, filename=None):
        """Generate a plain text report.

        Args:
            filename: Optional filename for the report.
                     Defaults to timestamp-based name.

        Returns:
            Path to the generated text report.
        """
        if filename is None:
            timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
            filename = f'report_{timestamp}.txt'

        filepath = os.path.join(self.output_dir, filename)

        # Get summaries
        parser_summary = self.parser.summarize()
        analyzer_summary = self.analyzer.get_summary()

        # Build text content
        content = f"""ASPECT SIMULATION REPORT
{'=' * 60}

Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

PARSER SUMMARY
{'-' * 60}
Total Lines: {parser_summary['total_lines']}
Errors Found: {parser_summary['errors_count']}
Timesteps Found: {parser_summary['timesteps_count']}

ANALYSIS RESULTS
{'-' * 60}
Total Errors: {analyzer_summary['total_errors']}
Failed Operations: {analyzer_summary['total_failures']}
Convergence Issues: {analyzer_summary['convergence_issues']}
Solver Warnings: {analyzer_summary['solver_warnings']}
NaN Occurrences: {analyzer_summary['nan_count']}
Memory Issues: {analyzer_summary['memory_issues']}
Timesteps Completed: {analyzer_summary['timesteps_completed']}

DETAILED FINDINGS
{'-' * 60}

ERRORS:
"""
        for i, error in enumerate(self.analyzer.analysis_results['error_lines'][:10], 1):
            content += f"{i}. {error}\n"

        if len(self.analyzer.analysis_results['error_lines']) > 10:
            content += f"... and {len(self.analyzer.analysis_results['error_lines']) - 10} more errors\n"

        content += f"\nCONVERGENCE FAILURES:\n\n"
        for i, failure in enumerate(self.analyzer.analysis_results['convergence_failures'][:5], 1):
            content += f"{i}. {failure}\n"

        content += f"\n{'=' * 60}\nReport generated by aspect-hpc-ai-monitor\n"

        with open(filepath, 'w') as f:
            f.write(content)

        return filepath

    def generate_all_reports(self):
        """Generate both markdown and text reports.

        Returns:
            Dictionary with paths to generated reports.
        """
        return {
            'markdown': self.generate_markdown_report(),
            'text': self.generate_text_report()
        }
